/*
	Clickbaitblock - blocks you from loading clickbait sites in chrome
    Copyright (C) 2015  Tiago Roque Medeiros

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
	
*/

var clickbaits = [	
	"collegehumor.com",
	"theblaze.com",
	"iflscience.com",
	"dorkly.com",
	"geeksaresexy.net",
	"zergnet.com",
	"joblo.com",
	"maxim.com",
	"wegotthiscovered.com",
	"cinemablend.com",
	"screenrant.com",
	"news.moviefone.com",
	"moviefone.com",
	"offbeatbride.com",
	"cheezburger.com",
	"cracked.com",
	"wimp.com",
	"new.damn.com",
	"damn.com",
	"metaspoon.com",
	"buzzfeed.com",
	"playbuzz.com",
	"clickhole.com",
	"ijreview.com",
	"zanzle.com",
	"bustle.com",
	"dailymail.co.uk",
	"drudgereport.com",
	"home.ijreview.com",
	"thepoliticalinsider.com",
	"ca.complex.com",
	"collective-evolution.com",
	"themindunleashed.org",
	"naturalnews.com",
	"heritage.org",
	"conservativetribune.com",
	"newsmax.com",
	"tpnn.com",
	"deadspin.com",
	"foodbabe.com",
	"clickhole.com",
	"fortafy-daily.com",
	"taldisparate.net",
	"upworthy.com",
	"positivemed.com",
	"viralchoka.net",
	"moviepilot.com",
	"vh1.com",
	"bitecharge.com",
	"viralfury.com",
	"dailymotion.com",
	"wittyfeed.com",
	"diply.com",
	"tv.bamargera.com",
	"bamargera.com",
	"mytop.fm",
	"clipuri.net",
	"boredomtherapy.com",
	"themighty.com",
	"facebooknow.info",
	"failyfailcenter.com",
	"reshareworthy.com",
	"twistedbeans.com",
	"mobilelikez.com",
	"allyourlolzarebelongtous.com",
	"crafinot.com",
	"hightimes.com",
	"guff.com",
	"bamargeraworld.com",
	"answers.com",
	"all-that-is-interesting.com",
	"ranker.com",
	"oola.com",
	"uproxx.com",
	"odometer.com",
	"cheeserank.com",
	"hellogiggles.com",
	"topix.com",
	"egokick.com",
	"cafemom.com",
	"distractify.com",
	"memes.com",
	"brainjet.com",
	"emgn.com",
	"jokemine.com",
	"good.is",
	"com-news.site",
	"clipd.com",
	"swifty.com",
	"ratemyjob.com",
	"poltell.com"
];
